- hosts: rs485
  tasks:
    - name: add nodejs repo
      shell: curl -sL https://deb.nodesource.com/setup_10.x

    - name: install nodejs
      apt:
        name: nodejs
        update_cache: yes

    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow

    - name: Apply settings
      reboot:

- hosts: core
  tasks:
    - name: Install python docker
      apt:
        name: python-setuptools, python-pip, python-docker
        update_cache: yes
