- hosts: localhost
  tasks:
    - uri:
        url: https://api.github.com/repos/bars66/WinterIsComingV2/releases/latest
        return_content: true
      register: json_reponse

    - get_url:
        url: "{{ json_reponse.json.assets[0].browser_download_url }}"
        dest: ./build.zip

- hosts: all
  tasks:
    - name: Create project dir
      file:
        path: /opt/WinterIsComingV2/
        state: directory
        mode: '0755'

    - name: Unarchive project
      unarchive:
        src: ./build.zip
        dest: /opt/WinterIsComingV2/

    - name: Unarchive project
      unarchive:
        src: ./build.zip
        dest: /opt/WinterIsComingV2/

    - name: Install packages
      shell: yarn install
      args:
        chdir: /opt/WinterIsComingV2/

- hosts: localhost
  tasks:
    - name: Remove build
      file:
        path: ./build.zip
        state: absent
