#- hosts: localhost
#  tasks:

#
#    - get_url:
#        url: '{{ json_reponse.json.assets[0].browser_download_url }}'
#        dest: ./build.zip

- hosts: rs485
  tasks:
    - uri:
        url: https://api.github.com/repos/bars66/WinterIsComingV2/releases/latest
        return_content: true
      register: json_reponse

    - name: Copy package
      copy:
        src: ../../out/wic-bridge.deb
        dest: ~/wic-bridge.deb

    - name: install package
      apt:
        deb: '{{ json_reponse.json.assets[0].browser_download_url }}'

    - name: Create env file
      become: true
      template:
        src: templates/bridge-env.conf
        dest: /opt/wic-bridge/packages/bridge/.env
    #
    - name: Copy systemd service file
      shell: cp /opt/wic-bridge/sys/systemd/wic-bridge.service /etc/systemd/system/wic-bridge.service

    - name: restart service
      systemd:
        state: restarted
        daemon_reload: yes
        name: wic-bridge.service
