- hosts: localhost
  tasks:
    - uri:
        url: https://api.github.com/repos/bars66/WinterIsComingV2/releases/latest
        return_content: true
      register: json_reponse

    - get_url:
        url: "{{ json_reponse.json.assets[0].browser_download_url }}"
        dest: ./build.zip

- hosts: all
  tasks:
    - name: Create project dir
      file:
        path: /opt/WinterIsComingV2/
        state: directory
        mode: '0755'

    - name: Unarchive project
      unarchive:
        src: ./build.zip
        dest: /opt/WinterIsComingV2/

    - name: Install packages
      shell: yarn install --prod --frozen-lockfile
      args:
        chdir: /opt/WinterIsComingV2/

    - name: Save hash
      shell: '[ "$(cat yarn.lock.hash)" != "$(md5sum yarn.lock)" ] && echo success || echo error'
      args:
        chdir: /opt/WinterIsComingV2/

- hosts: rs485
  tasks:
    - name: Create env file
      become: true
      template:
        src: templates/bridge-env.conf
        dest: /opt/WinterIsComingV2/packages/bridge/.env

    - name: Copy systemd service file
      shell: cp /opt/WinterIsComingV2/sys/systemd/winterIsComingBridge.service /etc/systemd/system/winterIsComingBridge.service

    - name: restart service
      systemd:
        state: restarted
        daemon_reload: yes
        name: winterIsComingBridge.service



- hosts: localhost
  tasks:
    - name: Remove build
      file:
        path: ./build.zip
        state: absent
