name: docker common image build

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: login
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: docker build -t docker.pkg.github.com/bars66/winteriscomingv2/wic:latest -f sys/docker/wic-build.dockerfile .

      - name: push
        run: docker push docker.pkg.github.com/bars66/winteriscomingv2/wic:latest
