name: bridge docker image build

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login
        run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t docker.pkg.github.com/bars66/winteriscomingv2/bridge:latest \
            --output "type=image,push=false" \
            --file ./sys/docker/bridge.dockerfile ./ \
            --push
